# 可选，将显示在 GitHub 存储库的“操作”选项卡中的工作流名称
name: Release CI

# 指定此工作流的触发器
on:
  push:
    branches: [ master ]

# 需要运行的作业组合
jobs:
  # 任务：创建 release 版本
  create-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

    steps:
      - uses: actions/checkout@v2
      # 查询版本号（tag）
      - name: Get commit ID
        id: commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"

      # 根据查询到的版本号创建 release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.commit_id.outputs.commit_id }}
          release_name: Release ${{ steps.commit_id.outputs.commit_id }}
          body: 'See the assets to download this version and install.'

  # 编译 Tauri
  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

     # 安装 Node.js
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # 安装 Rust
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev libasound2-dev librsvg2-dev patchelf

      # 安装依赖执行构建，以及推送 github release
      - name: Install app dependencies and build it
      # 这里的pubhome要修改为你package.json里面配置的编译命令
        run: npm install -g pnpm && pnpm install && pnpm tauri build
      - uses: tauri-apps/tauri-action@v0
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}